name: APK Yapici
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodları Çek (Checkout v4 yaptık)
      - uses: actions/checkout@v4

      # 2. Buildozer ile Derle
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # 3. APK'yı Yükle (Artifact v4 yaptık - Hatayı Çözen Yer Burası)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LFA-Uygulama
          path: bin/*.apk
